source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'TestApp' do
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'
    pod 'ImageSlideshow', '~> 1.4'
    pod "ImageSlideshow/Alamofire"
end